/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorProducto;
import java.awt.TextField;

/**
 *
 * @author Imagic1
 */
public class openActualizar extends javax.swing.JFrame {
    ControladorProducto cp;

    /**
     * Creates new form openActualizar
     */
    public openActualizar() {
        initComponents();
    }
    
    public void setControlador(ControladorProducto cp){
        this.cp = cp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        title_nombre_winact = new java.awt.Label();
        title_precio_winact = new java.awt.Label();
        title_inventario_winact = new java.awt.Label();
        input_nombre_winact = new java.awt.TextField();
        input_precio_winact = new java.awt.TextField();
        input_inventario_winact = new java.awt.TextField();
        panel1_red_top = new java.awt.Panel();
        title_windowActualizar = new java.awt.Label();
        bt_actualizar_winact = new javax.swing.JButton();

        jLabel1.setText("Ingrese los nuevos valores");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        title_nombre_winact.setFont(new java.awt.Font("Encode Sans Condensed Light", 0, 14)); // NOI18N
        title_nombre_winact.setText("NOMBRE");

        title_precio_winact.setText("PRECIO");

        title_inventario_winact.setText("INVENTARIO");

        input_nombre_winact.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_nombre_winact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nombre_winactActionPerformed(evt);
            }
        });

        panel1_red_top.setBackground(new java.awt.Color(153, 153, 0));

        title_windowActualizar.setAlignment(java.awt.Label.CENTER);
        title_windowActualizar.setFont(new java.awt.Font("Encode Sans Condensed SemiBold", 0, 14)); // NOI18N
        title_windowActualizar.setForeground(new java.awt.Color(255, 255, 255));
        title_windowActualizar.setText("INGRESE LOS NUEVOS DATOS");

        javax.swing.GroupLayout panel1_red_topLayout = new javax.swing.GroupLayout(panel1_red_top);
        panel1_red_top.setLayout(panel1_red_topLayout);
        panel1_red_topLayout.setHorizontalGroup(
            panel1_red_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1_red_topLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(title_windowActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        panel1_red_topLayout.setVerticalGroup(
            panel1_red_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1_red_topLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(title_windowActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        bt_actualizar_winact.setAction(bt_actualizar_winact.getAction());
        bt_actualizar_winact.setBackground(new java.awt.Color(153, 51, 0));
        bt_actualizar_winact.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_winact.setText("ACTUALIZAR PRODUCTO");
        bt_actualizar_winact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarProducto(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_inventario_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_precio_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_nombre_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_nombre_winact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_precio_winact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_inventario_winact, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(panel1_red_top, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_actualizar_winact, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1_red_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title_nombre_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_nombre_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(title_precio_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(input_precio_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_inventario_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_inventario_winact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(bt_actualizar_winact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nombre_winactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nombre_winactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nombre_winactActionPerformed

    private void actualizarProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProducto
        cp.eventoActualizar(this);
    }//GEN-LAST:event_actualizarProducto

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(openActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(openActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(openActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(openActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new openActualizar().setVisible(true);
            }
        });
    }

    
    
    
    
    public String getInput_inventario_winact() {
        return input_inventario_winact.getText();
    }

    public String getInput_nombre_winact() {
        return input_nombre_winact.getText();
    }

    public String getInput_precio_winact() {
        return input_precio_winact.getText();
    }
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_winact;
    private java.awt.TextField input_inventario_winact;
    private java.awt.TextField input_nombre_winact;
    private java.awt.TextField input_precio_winact;
    private javax.swing.JLabel jLabel1;
    private java.awt.Panel panel1_red_top;
    private java.awt.Label title_inventario_winact;
    private java.awt.Label title_nombre_winact;
    private java.awt.Label title_precio_winact;
    private java.awt.Label title_windowActualizar;
    // End of variables declaration//GEN-END:variables
}
