
package vista;

import controlador.ControladorProducto;
import java.awt.TextField;
import javax.swing.JTable;

/**
 *
 * @author Imagic1
 */
public class window_IApp extends javax.swing.JFrame {
    ControladorProducto cp;

    /**
     * Creates new form window_IApp
     */
    public window_IApp() {
        initComponents();
    }
    
    public void setControlador (ControladorProducto cp) {
        this.cp = cp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_Bienvenida = new java.awt.Label();
        jPanel_IngresoDatos = new javax.swing.JPanel();
        title_name = new javax.swing.JLabel();
        title_inventario = new javax.swing.JLabel();
        title_precio = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JButton();
        input_inventario = new java.awt.TextField();
        input_name = new java.awt.TextField();
        input_precio = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventario = new javax.swing.JTable();
        b_actualizar = new javax.swing.JButton();
        b_informe = new javax.swing.JButton();
        b_borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 5 Inventario de Productos");
        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(800, 450));

        Titulo_Bienvenida.setAlignment(java.awt.Label.CENTER);
        Titulo_Bienvenida.setBackground(new java.awt.Color(204, 204, 0));
        Titulo_Bienvenida.setFont(new java.awt.Font("Encode Sans Semi Condensed Medium", 1, 24)); // NOI18N
        Titulo_Bienvenida.setForeground(new java.awt.Color(51, 51, 0));
        Titulo_Bienvenida.setText("Bienvenido a InventariApp");

        jPanel_IngresoDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar NUEVO PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Encode Sans Semi Condensed", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel_IngresoDatos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_IngresoDatos.setFont(new java.awt.Font("Encode Sans Condensed Light", 0, 14)); // NOI18N

        title_name.setFont(new java.awt.Font("Encode Sans Condensed Light", 0, 14)); // NOI18N
        title_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_name.setText("NOMBRE");
        title_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        title_inventario.setFont(new java.awt.Font("Encode Sans Condensed Light", 0, 14)); // NOI18N
        title_inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_inventario.setText("INVENTARIO");

        title_precio.setFont(new java.awt.Font("Encode Sans Condensed Light", 0, 14)); // NOI18N
        title_precio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_precio.setText("PRECIO");

        BotonAgregar.setAction(BotonAgregar.getAction());
        BotonAgregar.setBackground(new java.awt.Color(153, 51, 0));
        BotonAgregar.setFont(new java.awt.Font("Encode Sans Condensed SemiBold", 0, 14)); // NOI18N
        BotonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setText("AGREGAR");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion_agregar(evt);
            }
        });

        input_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_inventario.setFont(new java.awt.Font("Encode Sans Semi Condensed", 0, 14)); // NOI18N
        input_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_inventarioActionPerformed(evt);
            }
        });

        input_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });

        input_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_precioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_IngresoDatosLayout = new javax.swing.GroupLayout(jPanel_IngresoDatos);
        jPanel_IngresoDatos.setLayout(jPanel_IngresoDatosLayout);
        jPanel_IngresoDatosLayout.setHorizontalGroup(
            jPanel_IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_IngresoDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel_IngresoDatosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel_IngresoDatosLayout.setVerticalGroup(
            jPanel_IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_IngresoDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_precio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Iventario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventario);

        b_actualizar.setAction(b_actualizar.getAction());
        b_actualizar.setBackground(new java.awt.Color(153, 153, 0));
        b_actualizar.setFont(new java.awt.Font("Encode Sans Condensed SemiBold", 0, 14)); // NOI18N
        b_actualizar.setForeground(new java.awt.Color(51, 0, 0));
        b_actualizar.setText("ACTUALIZAR");
        b_actualizar.setActionCommand("BORRAR");
        b_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_actualizarActionPerformed(evt);
                accion_actualizar(evt);
            }
        });

        b_informe.setAction(b_informe.getAction());
        b_informe.setBackground(new java.awt.Color(102, 0, 204));
        b_informe.setFont(new java.awt.Font("Encode Sans Condensed SemiBold", 0, 14)); // NOI18N
        b_informe.setForeground(new java.awt.Color(255, 255, 255));
        b_informe.setText("INFORME");
        b_informe.setActionCommand("BORRAR");
        b_informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_informeActionPerformed(evt);
                accion_informe(evt);
            }
        });

        b_borrar.setAction(b_borrar.getAction());
        b_borrar.setBackground(new java.awt.Color(153, 51, 0));
        b_borrar.setFont(new java.awt.Font("Encode Sans Condensed SemiBold", 0, 14)); // NOI18N
        b_borrar.setForeground(new java.awt.Color(255, 255, 255));
        b_borrar.setText("BORRAR");
        b_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_borrarActionPerformed(evt);
                accion_borrar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel_IngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(b_actualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_borrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_informe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(Titulo_Bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel_IngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_informe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel_IngresoDatos.getAccessibleContext().setAccessibleName("Agregar NUEVO PRODUCTO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void input_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_inventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_inventarioActionPerformed

    private void input_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_precioActionPerformed

    private void b_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_actualizarActionPerformed

    private void b_informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_informeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_informeActionPerformed

    private void b_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_borrarActionPerformed

    private void accion_agregar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accion_agregar
        cp.eventoAgregar();
    }//GEN-LAST:event_accion_agregar

    private void accion_borrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accion_borrar
        cp.eventoEliminar();
    }//GEN-LAST:event_accion_borrar

    private void accion_actualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accion_actualizar
        cp.openWindowAct();
    }//GEN-LAST:event_accion_actualizar

    private void accion_informe(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accion_informe
        cp.eventoInforme();
    }//GEN-LAST:event_accion_informe

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window_IApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window_IApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window_IApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window_IApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new window_IApp().setVisible(true);
            }
        });
    }
    
    
    
    
    
    
    

    public String getInput_inventario() {
        return input_inventario.getText();
    }

    public String getInput_name() {
        return input_name.getText();
    }

    public String getInput_precio() {
        return input_precio.getText();
    }

    public JTable getInventario() {
        return inventario;
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private java.awt.Label Titulo_Bienvenida;
    private javax.swing.JButton b_actualizar;
    private javax.swing.JButton b_borrar;
    private javax.swing.JButton b_informe;
    private java.awt.TextField input_inventario;
    private java.awt.TextField input_name;
    private java.awt.TextField input_precio;
    private javax.swing.JTable inventario;
    private javax.swing.JPanel jPanel_IngresoDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title_inventario;
    private javax.swing.JLabel title_name;
    private javax.swing.JLabel title_precio;
    // End of variables declaration//GEN-END:variables
}
